# Use the official Node.js 18 image as the base
FROM node:18

# Set the working directory inside the container
WORKDIR /

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# # Command to run the application
# RUN npx prisma db push

# RUN npm run test
