version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        DATABASE_URL: postgresql://root:root@db:5432/dev_plaza?schema=user-mgmt-db
    environment:
      DATABASE_URL: postgresql://root:root@db:5432/dev_plaza?schema=user-mgmt-db
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - test-network
    restart: on-failure
    command: bash -c " ls && [ -f prisma/schema.prisma ] && echo 'Schema File exists' && npx prisma db push && npm run test "

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dev_plaza
    networks:
      - test-network

networks:
  test-network:
    driver: bridge